server:
  port: 8080

spring:
  application:
    name: dormitory-management

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/dmdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1997mayue...
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
